name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install PostgreSQL 17 and dependencies
      run: |
        sudo apt-get install -y wget ca-certificates
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          postgresql-17 \
          postgresql-server-dev-17 \
          libgeos-dev \
          libproj-dev \
          libjson-c-dev \
          libsfcgal-dev \
          libxml2-dev \
          wget
        
    - name: Fetch and build dependencies
      run: |
        ./fetch-dependencies.sh
        
    - name: Build extension
      run: |
        make clean
        make
        
    - name: Install and test
      run: |
        sudo make install
        sudo -u postgres /usr/lib/postgresql/17/bin/pg_ctl -D /var/lib/postgresql/17/main -l /tmp/logfile start
        sleep 3
        sudo -u postgres createdb test_db
        sudo -u postgres psql test_db -c "CREATE EXTENSION geodesk_fdw;"
        sudo -u postgres psql test_db -c "\dx geodesk_fdw"